# ===== SERVER =====
server.port=8080

# ===== MySQL =====
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=ilkin
spring.datasource.password=123456


# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e7d0d2c8a87a9e2e1d3f0b6a
jwt.expiration=86400000

# ===== Swagger =====
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=az.ilkin.eis.controller
springdoc.default-produces-media-type=application/json